import { getSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Widgets from "../components/Widgets";
export default function Home({ session }) {
  if (!session) return <Login />;

  return (
    <div>
      <Head className="h-screen overflow-hidden bg-gray-100">
        <title>Basilbois</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      <main className="flex">
        {/* sidebar */}
        <Sidebar />
        {/* feed */}
        <Feed />
        {/* widgets */}
        <Widgets />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  //get the user
  console.log(context + "here");
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
}
